-- ═══════════════════════════════════════════════════════════════
--  Crème De La Style — full schema migration
--  Generated by live introspection of nfoeltjcmemcpwdwewbq on
--  2026-07-09. Structure + security only — NO row data, as
--  requested. Run once, top to bottom, in the NEW project's SQL
--  Editor (a fresh project's Postgres role setup handles GRANTs
--  differently than this one did — see the note at the bottom).
--
--  ⚠ ACTION REQUIRED before running: trg_push_activity_feed()
--  near the bottom hardcodes this OLD project's URL + anon key
--  to call the send-push Edge Function. Both REPLACE_WITH_* tokens
--  must be swapped for the NEW project's values (Settings → API)
--  once you have them, or push notifications will silently call
--  a project that no longer has this data. Search for REPLACE_WITH.
--
--  Scope: only Crème De La Style's 26 tables. This project also
--  hosts an unrelated classroom/WAEC app (students, questions,
--  transactions, access_codes) — deliberately excluded per your
--  choice; migrate that separately if/when needed.
-- ═══════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────
-- EXTENSIONS
-- ─────────────────────────────────────────────────────────
create extension if not exists pg_net with schema extensions;


-- ─────────────────────────────────────────────────────────
-- TABLES (created in dependency order)
-- ─────────────────────────────────────────────────────────

-- nominees — RLS enabled with zero policies in the source project
-- (locked to service_role/postgres only). Appears unused by the
-- live app (0 rows, superseded by votes.category_id/nominee_id).
create table public.nominees (
    id          uuid primary key default gen_random_uuid(),
    category_id text,
    name        text
);

create table public.system_settings (
    id                       serial primary key,
    event_date               timestamptz not null default '2026-11-26 18:00:00+00',
    updated_at               timestamptz default now(),
    show_live_results        boolean default false,
    lineup_revealed          boolean default false,
    is_registration_open     boolean not null default true,
    is_nomination_open       boolean not null default true,
    is_voting_open           boolean not null default false,
    show_tickets             boolean not null default true,
    show_judges              boolean not null default true,
    show_team                boolean not null default true,
    show_lineup              boolean not null default true,
    is_honorary_voting_open  boolean not null default false,
    show_pre_event           boolean default true,
    show_main_event          boolean default true,
    apply_fan_points         boolean default false,
    winner_id                uuid,
    show_volunteer           boolean not null default true,
    pre_event_date           timestamptz
);

create table public.notifications (
    id         uuid primary key default gen_random_uuid(),
    title      text not null,
    message    text not null,
    type       text not null default 'info',
    created_at timestamptz default now()
);

create table public.dispatches (
    id         uuid primary key default gen_random_uuid(),
    headline   text not null,
    message    text not null,
    tag        text not null default 'announcement'
               check (tag in ('announcement','update','media','urgent')),
    created_at timestamptz not null default now()
);

create table public.volunteers (
    id              uuid primary key default gen_random_uuid(),
    full_name       text not null,
    email           text not null,
    whatsapp_number text not null,
    team_preference text not null,
    is_approved     boolean not null default false,
    created_at      timestamptz not null default now()
);

create table public.gallery_media (
    id         uuid primary key default gen_random_uuid(),
    image_url  text not null,
    category   text not null check (category in ('photos','bts','livefeed')),
    created_at timestamptz not null default now(),
    caption    text
);

create table public.urgent_polls (
    id          uuid primary key default gen_random_uuid(),
    title       text not null,
    description text not null,
    options     jsonb not null,
    is_active   boolean not null default false,
    created_at  timestamptz not null default now()
);

create table public.contact_messages (
    id          uuid primary key default gen_random_uuid(),
    sender_name text,
    email       text,
    subject     text,
    message     text,
    created_at  timestamptz not null default now()
);

create table public.judges (
    id             uuid primary key default gen_random_uuid(),
    name           text not null,
    title          text not null,
    is_head        boolean default false,
    photo_url      text,
    bios           jsonb default '[]'::jsonb,
    sort_order     integer default 0,
    created_at     timestamptz not null default now(),
    social_handles text
);

create table public.team_members (
    id              uuid primary key default gen_random_uuid(),
    name            text not null,
    title           text not null,
    photo_url       text,
    bios            jsonb default '[]'::jsonb,
    sort_order      integer default 0,
    created_at      timestamptz not null default now(),
    social_handles  text,
    signature_quote text
);

create table public.event_timeline (
    id          uuid primary key default gen_random_uuid(),
    event_type  text not null check (event_type in ('mixer','main')),
    time_label  text not null,
    description text not null,
    sort_order  integer not null default 0,
    created_at  timestamptz not null default now()
);

create table public.sponsors (
    id         uuid primary key default gen_random_uuid(),
    name       text not null,
    logo_url   text,
    tier       text,
    created_at timestamptz default now()
);

create table public.journal_entries (
    id         uuid primary key default gen_random_uuid(),
    tag        text not null,
    title      text not null,
    excerpt    text not null,
    created_at timestamptz not null default now()
);

create table public.challenges (
    id            uuid primary key default gen_random_uuid(),
    title         text not null,
    description   text,
    starts_at     timestamptz,
    ends_at       timestamptz,
    marks         numeric,
    status        text not null default 'active' check (status in ('active','closed')),
    result_remark text,
    created_at    timestamptz default now()
);

create table public.activity_feed (
    id         uuid primary key default gen_random_uuid(),
    kind       text not null,
    title      text,
    message    text not null,
    tag        text,
    image_url  text,
    link_tab   text,
    created_at timestamptz not null default now()
);

create table public.user_roles (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null unique references auth.users(id) on delete cascade,
    role       text not null check (role in ('admin','judge')),
    created_at timestamptz default now()
);

create table public.tickets (
    id                uuid primary key default gen_random_uuid(),
    user_id           uuid references auth.users(id) on delete cascade,
    tier_name         text not null,
    amount            numeric not null,
    payment_status    text not null default 'pending',
    payment_reference text,
    entry_token       text unique,
    created_at        timestamptz default now(),
    is_used           boolean default false
);
-- Vestigial: guarded the old free "General Entry" tier, retired
-- when tickets moved to paid-only (Regular/VIP). Harmless to keep.
create unique index one_free_ticket_per_user on public.tickets (user_id) where (tier_name = 'General Entry');

create table public.contestants (
    id               uuid primary key default gen_random_uuid(),
    user_id          uuid references auth.users(id) on delete cascade,
    full_name        text not null,
    email            text,
    phone            text,
    department       text,
    height           numeric,
    waist            numeric,
    hips             numeric,
    stat_unit        text default 'cm',
    social_handles   text,
    tiktok           text,
    headshot_url     text,
    fullbody_url     text,
    about_me         text,
    why_picked       text,
    is_approved      boolean not null default false,
    created_at       timestamptz default now(),
    age              integer,
    gender           text,
    level            text,
    clothing_size    text,
    shoe_size        text,
    experience       text,
    video_url        text,
    payment_ref      text,
    chest            numeric,
    shoulder_width   numeric,
    inseam           numeric,
    bio              text,
    favorite_quote   text,
    vote_count       integer default 0,
    payment_verified boolean default false,
    is_featured      boolean default false
);

create table public.nominations (
    id                uuid primary key default gen_random_uuid(),
    user_id           uuid references auth.users(id) on delete set null,
    nominee_name      text not null,
    category          text not null,
    social_handle     text,
    reason            text,
    whatsapp_number   text,
    created_at        timestamptz default now(),
    email             text,
    payment_ref       text,
    amount_paid       integer default 200,
    payment_confirmed boolean default false
);

create table public.registrations (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid references auth.users(id) on delete set null,
    full_name  text not null,
    email      text not null,
    phone      text,
    department text,
    type       text not null,
    created_at timestamptz default now()
);

create table public.votes (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    category_id text not null,
    nominee_id  text not null,
    created_at  timestamptz not null default now(),
    unique (user_id, category_id)
);

create table public.push_subscriptions (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid references auth.users(id) on delete cascade,
    endpoint   text not null unique,
    p256dh     text not null,
    auth_key   text not null,
    created_at timestamptz default now()
);

create table public.scores (
    id                 uuid primary key default gen_random_uuid(),
    judge_id           uuid not null references auth.users(id) on delete cascade,
    contestant_id      uuid not null references public.contestants(id) on delete cascade,
    look_category      text not null check (look_category in ('professional','y2k','trad','met_gala')),
    criteria_breakdown jsonb not null,
    look_total         integer not null check (look_total >= 5 and look_total <= 50),
    judge_comment      text not null,
    created_at         timestamptz default now(),
    notes              text,
    unique (judge_id, contestant_id, look_category)
);

create table public.contestant_media (
    id            uuid primary key default gen_random_uuid(),
    contestant_id uuid references public.contestants(id) on delete cascade,
    media_url     text not null,
    media_type    text not null check (media_type in ('image','video')),
    created_at    timestamptz not null default now(),
    caption       text
);

create table public.poll_votes (
    id         uuid primary key default gen_random_uuid(),
    poll_id    uuid references public.urgent_polls(id),
    option     text not null,
    created_at timestamptz not null default now()
);

create table public.challenge_results (
    id           uuid primary key default gen_random_uuid(),
    challenge_id uuid not null references public.challenges(id) on delete cascade,
    position     integer not null,
    name         text not null,
    points       numeric,
    created_at   timestamptz default now()
);


-- ─────────────────────────────────────────────────────────
-- ENABLE ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────
alter table public.nominees            enable row level security;
alter table public.system_settings     enable row level security;
alter table public.notifications       enable row level security;
alter table public.dispatches          enable row level security;
alter table public.volunteers          enable row level security;
alter table public.gallery_media       enable row level security;
alter table public.urgent_polls        enable row level security;
alter table public.contact_messages    enable row level security;
alter table public.judges              enable row level security;
alter table public.team_members        enable row level security;
alter table public.event_timeline      enable row level security;
alter table public.sponsors            enable row level security;
alter table public.journal_entries     enable row level security;
alter table public.challenges          enable row level security;
alter table public.activity_feed       enable row level security;
alter table public.user_roles          enable row level security;
alter table public.tickets             enable row level security;
alter table public.contestants         enable row level security;
alter table public.nominations         enable row level security;
alter table public.registrations       enable row level security;
alter table public.votes               enable row level security;
alter table public.push_subscriptions  enable row level security;
alter table public.scores              enable row level security;
alter table public.contestant_media    enable row level security;
alter table public.poll_votes          enable row level security;
alter table public.challenge_results   enable row level security;


-- ─────────────────────────────────────────────────────────
-- FUNCTIONS
-- ─────────────────────────────────────────────────────────

create or replace function public.is_admin()
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  return exists (
    select 1
    from public.user_roles
    where user_roles.user_id = auth.uid()
    and user_roles.role = 'admin'
  );
end;
$function$;

create or replace function public.get_my_role()
returns text
language sql
stable security definer
as $function$
  select role from user_roles where user_id = auth.uid() limit 1;
$function$;

create or replace function public.get_user_count()
returns bigint
language sql
stable security definer
set search_path to 'public'
as $function$
    select count(*) from auth.users;
$function$;

create or replace function public.log_activity(p_kind text, p_title text, p_message text, p_tag text, p_image text, p_link text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    insert into activity_feed(kind, title, message, tag, image_url, link_tab)
    values (p_kind, p_title, p_message, p_tag, p_image, p_link);
end;
$function$;

create or replace function public.confirm_ticket_payment(ticket_id uuid)
returns void
language plpgsql
security definer
as $function$
BEGIN
  UPDATE tickets SET payment_status = 'paid' WHERE id = ticket_id;
END;
$function$;

create or replace function public.confirm_nomination_payment(nom_id uuid)
returns void
language plpgsql
security definer
as $function$
BEGIN
  UPDATE nominations SET payment_confirmed = true WHERE id = nom_id;
END;
$function$;

create or replace function public.enforce_contestant_cap()
returns trigger
language plpgsql
security definer
as $function$
begin
    if (select count(*) from contestants where payment_ref is not null) >= 30 then
        raise exception 'REGISTRATION_FULL';
    end if;
    return new;
end;
$function$;

create or replace function public.force_pending_on_paid_tickets()
returns trigger
language plpgsql
as $function$
begin
    if new.amount > 0 then
        new.payment_status := 'pending';
    end if;
    return new;
end;
$function$;

create or replace function public.cast_fan_vote(p_contestant_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_uid uuid := auth.uid();
begin
    if v_uid is null then
        return jsonb_build_object('error', 'not authenticated');
    end if;
    insert into public.votes (user_id, category_id, nominee_id)
    values (v_uid, 'fan_favourite', p_contestant_id)
    on conflict (user_id, category_id)
    do update set nominee_id = excluded.nominee_id, created_at = now();
    return jsonb_build_object('ok', true);
end;
$function$;

create or replace function public.cast_fan_vote(p_contestant_id uuid)
returns void
language plpgsql
security definer
as $function$
BEGIN
  INSERT INTO votes (user_id, category_id, nominee_id)
  VALUES (auth.uid(), 'fan_favourite', p_contestant_id)
  ON CONFLICT (user_id, category_id)
  DO UPDATE SET nominee_id = EXCLUDED.nominee_id;
END;
$function$;

create or replace function public.trg_log_dispatch()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('dispatch', new.headline, new.message, coalesce(new.tag,'announcement'), null, 'home');
    return new;
end;
$function$;

create or replace function public.trg_log_contestant_featured()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    if new.is_featured is true and (old.is_featured is distinct from true) then
        perform log_activity('contestant', new.full_name,
            new.full_name || ' just joined The Lineup' || case when new.department is not null then ' · ' || new.department else '' end,
            null, new.headshot_url, 'lineup');
    end if;
    return new;
end;
$function$;

create or replace function public.trg_log_gallery()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('gallery', null,
        case when new.caption is not null then '📸 New in the Gallery: ' || new.caption else '📸 New in the Gallery' end,
        null, new.image_url, 'gallery');
    return new;
end;
$function$;

create or replace function public.trg_log_challenge()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('challenge', new.title,
        'New challenge: ' || new.title || case when new.marks is not null then ' · ' || new.marks::text || ' marks' else '' end,
        null, null, 'challenges');
    return new;
end;
$function$;

create or replace function public.trg_log_challenge_closed()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    if new.status = 'closed' and (old.status is distinct from 'closed') then
        perform log_activity('challenge_result', new.title, 'Results are in: ' || new.title, null, null, 'challenges');
    end if;
    return new;
end;
$function$;

create or replace function public.trg_log_poll()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    if new.is_active is true then
        perform log_activity('poll', new.title, '🗳️ New poll: ' || new.title || ' — have your say!', null, null, 'home');
    end if;
    return new;
end;
$function$;

create or replace function public.trg_log_sponsor()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('sponsor', new.name, '🤝 ' || new.name || ' just came on board as a sponsor!', null, new.logo_url, 'event');
    return new;
end;
$function$;

create or replace function public.trg_log_team()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('team', new.name, '👥 ' || new.name || ' joined the organizing team', null, new.photo_url, 'team');
    return new;
end;
$function$;

create or replace function public.trg_log_judge()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    perform log_activity('judge', new.name, '⚖️ ' || new.name || ' announced as a judge', null, new.photo_url, 'judges');
    return new;
end;
$function$;

create or replace function public.trg_log_ticket_paid()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
    buyer_name text;
    other_count int;
    msg text;
begin
    if new.payment_status = 'paid' and (tg_op = 'INSERT' or old.payment_status is distinct from 'paid') then
        select coalesce(nullif(trim(raw_user_meta_data->>'full_name'), ''), split_part(email, '@', 1))
          into buyer_name
          from auth.users where id = new.user_id;

        select count(*) into other_count from tickets
          where tier_name = new.tier_name and payment_status = 'paid';
        other_count := greatest(other_count - 1, 0);

        msg := coalesce(buyer_name, 'Someone')
             || case when other_count > 0
                    then ' and ' || other_count || case when other_count = 1 then ' other' else ' others' end
                    else ''
                end
             || ' just purchased a ' || new.tier_name || ' ticket 🎟️';

        perform log_activity('ticket', null, msg, null, null, 'tickets');
    end if;
    return new;
end;
$function$;

create or replace function public.trg_log_app_controls()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
    if new.is_registration_open is distinct from old.is_registration_open then
        perform log_activity('control', null, case when new.is_registration_open
            then '📝 Contestant Registration is now OPEN!' else '📝 Contestant Registration is now closed.' end,
            null, null, 'register');
    end if;
    if new.is_nomination_open is distinct from old.is_nomination_open then
        perform log_activity('control', null, case when new.is_nomination_open
            then '✨ Nominations are now OPEN — go nominate!' else '✨ Nominations are now closed.' end,
            null, null, 'nominate');
    end if;
    if new.is_voting_open is distinct from old.is_voting_open then
        perform log_activity('control', null, case when new.is_voting_open
            then '🗳️ Fan Favourite Voting is now OPEN!' else '🗳️ Voting is now closed.' end,
            null, null, 'vote');
    end if;
    if new.show_tickets is distinct from old.show_tickets then
        perform log_activity('control', null, case when new.show_tickets
            then '🎟️ Ticket sales are now OPEN!' else '🎟️ Ticket sales are now closed.' end,
            null, null, 'tickets');
    end if;
    if new.show_lineup is distinct from old.show_lineup then
        perform log_activity('control', null, case when new.show_lineup
            then '👗 The Lineup has been revealed!' else '👗 The Lineup is hidden for now.' end,
            null, null, 'lineup');
    end if;
    if new.show_judges is distinct from old.show_judges then
        perform log_activity('control', null, case when new.show_judges
            then '⚖️ Meet the Judges — now revealed!' else '⚖️ Judges panel is hidden for now.' end,
            null, null, 'judges');
    end if;
    if new.show_team is distinct from old.show_team then
        perform log_activity('control', null, case when new.show_team
            then '👥 Meet the Team — now revealed!' else '👥 Team page is hidden for now.' end,
            null, null, 'team');
    end if;
    if new.show_volunteer is distinct from old.show_volunteer then
        perform log_activity('control', null, case when new.show_volunteer
            then '🙋 Volunteer signups are now OPEN!' else '🙋 Volunteer signups are now closed.' end,
            null, null, 'volunteer');
    end if;
    return new;
end;
$function$;

-- ⚠ REPLACE the URL and anon key below with the NEW project's own
-- values (Settings → API → Project URL / anon public key) once the
-- new project exists. Left as the old project's values would call
-- a send-push function that no longer has any subscribers.
create or replace function public.trg_push_activity_feed()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
begin
    perform net.http_post(
        url     := 'REPLACE_WITH_NEW_PROJECT_URL/functions/v1/send-push',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer REPLACE_WITH_NEW_PROJECT_ANON_KEY',
            'apikey', 'REPLACE_WITH_NEW_PROJECT_ANON_KEY'
        ),
        body    := jsonb_build_object(
            'title', coalesce(new.title, 'Crème De La Style'),
            'body', new.message,
            'link_tab', new.link_tab,
            'image_url', new.image_url
        )
    );
    return new;
end;
$function$;


-- ─────────────────────────────────────────────────────────
-- TRIGGERS
-- ─────────────────────────────────────────────────────────
create trigger on_activity_feed_push after insert on public.activity_feed
    for each row execute function public.trg_push_activity_feed();

create trigger on_challenge_insert after insert on public.challenges
    for each row execute function public.trg_log_challenge();
create trigger on_challenge_closed after update on public.challenges
    for each row execute function public.trg_log_challenge_closed();

create trigger contestant_cap_trigger before insert on public.contestants
    for each row execute function public.enforce_contestant_cap();
create trigger on_contestant_featured after update on public.contestants
    for each row execute function public.trg_log_contestant_featured();

create trigger on_dispatch_insert after insert on public.dispatches
    for each row execute function public.trg_log_dispatch();

create trigger on_gallery_insert after insert on public.gallery_media
    for each row execute function public.trg_log_gallery();

create trigger on_judge_insert after insert on public.judges
    for each row execute function public.trg_log_judge();

create trigger on_sponsor_insert after insert on public.sponsors
    for each row execute function public.trg_log_sponsor();

create trigger on_app_controls_update after update on public.system_settings
    for each row execute function public.trg_log_app_controls();

create trigger on_team_insert after insert on public.team_members
    for each row execute function public.trg_log_team();

create trigger trg_force_pending_tickets before insert on public.tickets
    for each row execute function public.force_pending_on_paid_tickets();
create trigger on_ticket_paid after insert or update on public.tickets
    for each row execute function public.trg_log_ticket_paid();

create trigger on_poll_insert after insert on public.urgent_polls
    for each row execute function public.trg_log_poll();


-- ─────────────────────────────────────────────────────────
-- RLS POLICIES  (reproduced exactly as they exist in the
-- source project, including historical overlap/duplication
-- from iterative development — see closing note)
-- ─────────────────────────────────────────────────────────

-- activity_feed
create policy "Public read activity_feed" on public.activity_feed
    for select using (true);
create policy "Admins delete activity_feed" on public.activity_feed
    for delete to authenticated using (is_admin());

-- challenges
create policy "Public read challenges" on public.challenges
    for select using (true);
create policy "Admins manage challenges" on public.challenges
    for all to authenticated using (is_admin()) with check (is_admin());

-- challenge_results
create policy "Public read challenge results" on public.challenge_results
    for select using (true);
create policy "Admins manage challenge results" on public.challenge_results
    for all to authenticated using (is_admin()) with check (is_admin());

-- contact_messages
create policy "cm_sel" on public.contact_messages
    for select using (true);
create policy "cm_ins" on public.contact_messages
    for insert with check (true);

-- contestant_media
create policy "cm_sel" on public.contestant_media
    for select using (true);
create policy "cm_ins" on public.contestant_media
    for insert with check (true);
create policy "cm_upd" on public.contestant_media
    for update using (true) with check (true);
create policy "cm_del" on public.contestant_media
    for delete using (true);
create policy "Admins manage contestant media" on public.contestant_media
    for all to authenticated using (is_admin()) with check (is_admin());

-- contestants
create policy "contestants_select" on public.contestants
    for select using (is_approved = true);
create policy "contestants_read_all" on public.contestants
    for select using (
        (is_approved = true) or (auth.uid() = user_id) or
        exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = any (array['admin','judge']))
    );
create policy "Admins read all contestants" on public.contestants
    for select using (
        (is_approved = true) or (auth.uid() = user_id) or
        exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin')
    );
create policy "contestants_insert" on public.contestants
    for insert with check (auth.uid() = user_id);
create policy "Admins insert contestants" on public.contestants
    for insert to authenticated with check (is_admin());
create policy "contestants_update" on public.contestants
    for update using (auth.uid() = user_id);
create policy "Admins update contestants" on public.contestants
    for update to authenticated using (is_admin()) with check (is_admin());
create policy "Admins can delete contestants" on public.contestants
    for delete to authenticated using (is_admin());

-- dispatches
create policy "Public read dispatches" on public.dispatches
    for select using (true);
create policy "Admins insert dispatches" on public.dispatches
    for insert with check (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));

-- event_timeline
create policy "tl_sel" on public.event_timeline for select using (true);
create policy "tl_ins" on public.event_timeline for insert with check (true);
create policy "tl_upd" on public.event_timeline for update using (true) with check (true);
create policy "tl_del" on public.event_timeline for delete using (true);

-- gallery_media
create policy "gallery_select_all" on public.gallery_media for select using (true);
create policy "gallery_insert_auth" on public.gallery_media for insert with check (true);
create policy "gallery_delete_auth" on public.gallery_media for delete using (true);

-- journal_entries
create policy "Public read journal_entries" on public.journal_entries
    for select using (true);
create policy "Admins insert journal_entries" on public.journal_entries
    for insert with check (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));
create policy "Admins update journal_entries" on public.journal_entries
    for update using (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));
create policy "Admins delete journal_entries" on public.journal_entries
    for delete using (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));

-- judges
create policy "judges_sel" on public.judges for select using (true);
create policy "judges_all" on public.judges for all using (true) with check (true);

-- nominations
create policy "nominations_select" on public.nominations
    for select using (auth.uid() = user_id);
create policy "Users read own nominations" on public.nominations
    for select to authenticated using (user_id = auth.uid());
create policy "nominations_insert" on public.nominations
    for insert with check (auth.uid() = user_id);
create policy "Authenticated users can insert nominations" on public.nominations
    for insert to authenticated with check (true);
create policy "Admin full access nominations" on public.nominations
    for all to authenticated using (get_my_role() = 'admin') with check (get_my_role() = 'admin');

-- notifications
create policy "notifs_select" on public.notifications for select using (true);
create policy "Admins insert notifications" on public.notifications
    for insert with check (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));

-- poll_votes
create policy "votes_sel" on public.poll_votes for select using (true);
create policy "votes_ins" on public.poll_votes for insert with check (true);

-- push_subscriptions
create policy "Users manage own push subscription" on public.push_subscriptions
    for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- registrations
create policy "registrations_select" on public.registrations
    for select using (auth.uid() = user_id);
create policy "registrations_insert" on public.registrations
    for insert with check (auth.uid() = user_id);

-- scores
create policy "scores_select" on public.scores
    for select using (get_my_role() = any (array['judge','admin']));
create policy "scores_read_auth" on public.scores
    for select using (auth.role() = 'authenticated');
create policy "Anyone can view scores" on public.scores
    for select using (true);
create policy "scores_insert" on public.scores
    for insert with check (auth.uid() = judge_id and get_my_role() = any (array['judge','admin']));
create policy "Judges update own scores" on public.scores
    for update using (auth.uid() = judge_id and exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'judge'));
create policy "Judges can save their own scores" on public.scores
    for all to authenticated using (auth.uid()::text = judge_id::text) with check (auth.uid()::text = judge_id::text);

-- sponsors
create policy "sp_sel" on public.sponsors for select using (true);
create policy "Public read sponsors" on public.sponsors for select using (true);
create policy "sp_ins" on public.sponsors for insert with check (true);
create policy "sp_upd" on public.sponsors for update using (true) with check (true);
create policy "sp_del" on public.sponsors for delete using (true);

-- system_settings
create policy "Anyone can read settings" on public.system_settings for select using (true);
create policy "settings_select" on public.system_settings for select using (true);
create policy "Admins can update settings" on public.system_settings
    for update using (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));
create policy "Admins update system_settings" on public.system_settings
    for update to authenticated using (is_admin()) with check (is_admin());

-- team_members
create policy "team_sel" on public.team_members for select using (true);
create policy "team_all" on public.team_members for all using (true) with check (true);

-- tickets
create policy "tickets_select" on public.tickets
    for select using (auth.uid() = user_id);
create policy "Users can read own tickets" on public.tickets
    for select to authenticated using (user_id = auth.uid());
create policy "tickets_admin_select" on public.tickets
    for select using (get_my_role() = 'admin');
create policy "Admin can read all tickets" on public.tickets
    for select to authenticated using (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));
create policy "tickets_insert" on public.tickets
    for insert with check (auth.uid() = user_id);
create policy "tickets_update" on public.tickets
    for update using (true);
create policy "Admin can update tickets" on public.tickets
    for update to authenticated using (exists (select 1 from user_roles where user_roles.user_id = auth.uid() and user_roles.role = 'admin'));

-- urgent_polls
create policy "polls_all" on public.urgent_polls for all using (true) with check (true);

-- user_roles
create policy "roles_select" on public.user_roles for select using (auth.uid() = user_id);
create policy "Admin can read user_roles" on public.user_roles
    for select to authenticated using (get_my_role() = 'admin');

-- volunteers
create policy "volunteers_select_all" on public.volunteers for select using (true);
create policy "volunteers_insert_all" on public.volunteers for insert with check (true);
create policy "volunteers_update_admin" on public.volunteers for update using (true);

-- votes
create policy "votes_select" on public.votes for select using (true);
create policy "votes_select_all" on public.votes for select using (true);
create policy "votes_insert_own" on public.votes for insert with check (auth.uid() = user_id);
create policy "votes_insert" on public.votes for insert to authenticated with check (auth.uid() = user_id);
create policy "votes_update" on public.votes for update to authenticated using (auth.uid() = user_id);
create policy "votes_delete_own" on public.votes for delete using (auth.uid() = user_id);
create policy "Users can vote" on public.votes for all using (auth.uid() = user_id);

-- nominees: RLS enabled, zero policies — locked down, matching source exactly


-- ─────────────────────────────────────────────────────────
-- REALTIME
-- ─────────────────────────────────────────────────────────
-- urgent_polls was correctly registered in the source project.
-- activity_feed SHOULD have been too (the frontend has always
-- expected instant live-feed updates) but that step was missed
-- there — included here from day one so the new project doesn't
-- inherit the same gap.
alter publication supabase_realtime add table public.urgent_polls;
alter publication supabase_realtime add table public.activity_feed;


-- ─────────────────────────────────────────────────────────
-- GRANTS
-- ─────────────────────────────────────────────────────────
-- Learned the hard way in the source project: tables created via
-- the SQL Editor don't automatically pick up the anon/authenticated/
-- service_role grants that the dashboard's Table Editor adds for
-- free — RLS policies alone are not enough, Postgres also needs the
-- base table GRANT as a separate layer. Every table above already
-- has RLS enabled, so granting broadly here does not bypass a
-- single policy above; RLS remains the only real access control.
-- The ALTER DEFAULT PRIVILEGES lines make every table created from
-- now on inherit this automatically, closing the gap for good.

grant select, insert, update, delete on all tables in schema public to authenticated;
grant select                        on all tables in schema public to anon;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

alter default privileges in schema public
    grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
    grant select on tables to anon;
alter default privileges in schema public
    grant select, insert, update, delete on tables to service_role;
alter default privileges in schema public
    grant usage, select on sequences to authenticated, service_role;


-- ═══════════════════════════════════════════════════════════════
--  NOT covered by this script (out of scope / needs separate work):
--
--  1. Storage buckets — contestant-headshots, contestant-fullbody,
--     contestant-videos, gallery-media, people-photos. These live
--     in the storage schema, not public, and hold real files, not
--     just structure. Recreate the buckets + their policies
--     manually in the new project (Storage → New bucket), then
--     move the actual files separately from this schema-only script.
--
--  2. auth.users — Supabase-managed, not part of "your" schema.
--     Your manual CSV move handles the actual accounts/rows; every
--     FK above already points at auth.users(id) correctly and will
--     just work once matching users exist in the new project.
--
--  3. Row data for all 26 tables — deliberately excluded, per your
--     instruction, since you're moving records via CSV yourself.
--
--  4. The Edge Functions (verify-flw-payment, send-push) — these
--     aren't part of the Postgres schema at all and must be
--     redeployed from source (already in this repo under
--     supabase/functions/) plus their secrets re-entered in the
--     new project's dashboard.
--
--  Also worth knowing: several tables above carry duplicate or
--  overlapping RLS policies (e.g. contestants has 3 separate SELECT
--  policies achieving similar goals via different mechanisms —
--  is_admin(), get_my_role(), and inline EXISTS checks). None of
--  this is broken — permissive policies just OR together — but it
--  reflects iterative history rather than a clean design. This
--  script reproduces it exactly as requested ("perfectly recreate"),
--  but it's a reasonable candidate for a future cleanup pass in
--  the new project once you're confident everything still works.
-- ═══════════════════════════════════════════════════════════════
